### ISSUE TITLE
Could not pass event PlayerQuitEvent to PowerBoard v3.6.3

### ISSUE THREAD

**Issue by nanana90** [Xitee1/Scoreboard#63]
**Describe the bug**
```
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
    at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:637)
    at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1141)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
    at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:493)
    at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:556)
    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:282)
    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:264)
    at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:202)
    at org.bukkit.craftbukkit.scoreboard.CraftScoreboard.getTeams(CraftScoreboard.java:21)
    at PowerBoard-3.6.3.jar//de.xite.scoreboard.modules.board.ScoreboardPlayer.removeScoreboard(ScoreboardPlayer.java:155)
    at PowerBoard-3.6.3.jar//de.xite.scoreboard.listeners.JoinQuitListener.onQuit(JoinQuitListener.java:61)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor517.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:611)
    at net.minecraft.server.players.PlayerLi
```

**To Reproduce**
1. Paper System
2. Use SimpleScore 
...

**Screenshots**

**Please complete the following information:**
 - Server version: Paper 1.20.6
 - Plugin version 3.6.3
**Additional information**

The Problem must be "this.wrapped"

<img width="363" alt="image" src="https://github.com/user-attachments/assets/b4405ad6-859f-4af0-8303-db95261e4566" />

```yaml
# ####################################################################################################
# ## PowerBoard: Scoreboard + Tablist + Prefix + Chat | Animated                                   ###
# ##                                                                                               ###
# ## Wiki: https://github.com/Xitee1/PowerBoard/wiki                                               ###
# ## Need some help? Support is given on our Discord Server:  https://discord.gg/VqK3ctsbz7        ###
# ## Found a bug? Report it either on GitHub or Discord.                                           ###
# ##                                                                                               ###
# ## (For developers) Source-Code: https://github.com/Xitee1/PowerBoard                            ###
# ####################################################################################################

# Before reaching out to support, read this!!
# Be careful when modifying the config! It is very sensitive to typing mistakes.
# A space too much or a missing ' and the plugin no longer works.
# To prevent these errors, ONLY modify the VALUES! Also keep an eye on the single quotes (don't remove them!).

# ##############
# ## Modules ###
# ##############
scoreboard: false # enable/disable the scoreboard
scoreboard-default: scoreboard # The scoreboard that will be set after a player joins the server
scoreboard-advanced-settings:
  use-existing-scoreboard: false # Always leave this false unless you use another scoreboard/rank plugin and have issues. In this case the option might fix issues with other plugins.

tablist:
  text: false # enable/disable the header/footers
  text-default: tablist # The tablist that will be set after a player joins the server
  ranks: true # enable/disable the rank system (only tablist)

chat:
  ranks: true # enable/disable the chat system
  colorperm: chat.color # The permission to use colorcodes in chat. To disable (preventing all players from using colors in chat), set it to "none".
  allowHexColors: true # Allow players to use hex colors in chat. It uses the 'colorperm' permission.

# ############
# ## Ranks ###
# ############
ranks:
  # You can use the following permission systems:
  # - none (the player needs the specified permission)
  # - LuckPerms (Features: Separate admin & owner rank's, auto update (no rejoin needed after group change - only API!), (optional) use prefixes you have set in luckperms)
  # - API (Only for devs - set this if you want to use the PowerBoard API only)
  # For more infos visit the wiki!
  permissionsystem: LuckPerms
  
  update-interval: -1 # Interval for automatically updating the ranks (in minutes). Useful if placeholders in prefixes/suffixes are used. Set to -1 to disable (default).
  
  options:
    show-prefix-in-tab: true # In case you have another plugin for the tablist prefix.
    show-suffix-in-tab: true
    use-player-list-name: false # This allows you to use hex colors for the player name. It also disables the prefix/suffix above the player's head.
    try-player-head-with-pln: false # Only active if 'use-player-list-name' is true. This option shows the prefix/suffix above the player's head again if it doesn't exceed the char limit.
  
  # If you want to sync all your prefixes with all your servers or just want to use the prefixes that you have set for the groups in
  # LuckPerms, enable this setting. But make sure that you have configured the LuckPerms groups properly! More infos are in the wiki.
  luckperms-api:
    enable: true
    prefix-suffix-space: false # Set a space behind the prefix and in front of the suffix
    chat-layout: '%prefix% %player_name% §7» ' # This is the fallback chat-prefix if there is no specific for the rank
    chat-prefix:
      owner: '#ffb7c5&lO#d596bf&lw#aa75b8&ln#8054b2&le#5533ab&lr §8| §7%player_name% §f&l» '
      admin: '§cAdmin §7| &c%player_name% §7» '
      player: '§7Player | %player_name% » '
  
  # ## (If you have LuckPerms API enabled, ignore the rank list in this config.)
  # ## You can add as many ranks as you want.
  # ## Note: There's a limit of 64 chars in the prefix/suffix. Depending on your MC version, this limit can be higher or lower.
  # ##       If you are unsure, just try it out after how much chars it stops working.
  # ##       The chat prefix does not have these limits.
  list:
    owner:
      permission: rank.owner # If the perm system above is "none", use a permission here. If it's not "none", use the group name instead (E.g. 'owner' instead of 'rank.leitung').
      prefix: '#ffb7c5&lO#d596bf&lw#aa75b8&ln#8054b2&le#5533ab&lr §8| §7'
      suffix: ''
      chatPrefix: '#ffb7c5&lO#d596bf&lw#aa75b8&ln#8054b2&le#5533ab&lr §8| §7%player_name%
        » #fc0c0c'
      placeholder-name: owner # This will replace the %player_rank% placeholder
    admin:
      permission: rank.admin
      prefix: '#f9cbfb&lA#c5d8de&ld#90e5c0&lm#5cf2a3&li#27ff85&ln §8| §7'
      suffix: ''
      chatPrefix: '#f9cbfb&lA#e8cff1&ld#d6d4e7&lm#c5d8de&li#b3dcd4&ln#a2e1ca&li#90e5c0&ls#7fe9b6&lt#6deeac&lr#5cf2a3&la#4af699&lt#39fb8f&lo#27ff85&lr
        §8| §7%player_name% » #fc0c0c'
      placeholder-name: admin
    dev:
      permission: rank.dev
      prefix: '#222222Dev §8| §7'
      suffix: ''
      chatPrefix: '#222222Developer §8| §7%player_name% » #fc0c0c'
      placeholder-name: dev
    content:
      permission: rank.content
      prefix: '#FF5555Content §8| §7'
      suffix: ''
      chatPrefix: '#FF5555Content §8| §7%player_name% » #fc0c0c'
      placeholder-name: Content
    mod:
      permission: rank.mod
      prefix: '#FF5555Mod §8| §7'
      suffix: ''
      chatPrefix: '#FF5555Moderator §8| §7%player_name% » #fc0c0c'
      placeholder-name: Mod
    team:
      permission: rank.team
      prefix: '#FF5555Team §8| §7'
      suffix: ''
      chatPrefix: '#FF5555Team §8| §7%player_name% » #fc0c0c'
      placeholder-name: Team
    beta:
      permission: rank.beta
      prefix: '#ffffffBeta §8| §7'
      suffix: ''
      chatPrefix: '#ffffffBeta§7-#ff0000Tester §8| §7%player_name% » #fc0c0c'
      placeholder-name: Beta
    freund:
      permission: rank.freund
      prefix: '#7cd9ffFreund §8| §7'
      suffix: ''
      chatPrefix: '#7cd9ffFreund §8| §7%player_name% » #f5f5dc'
      placeholder-name: Freund
    streamer:
      permission: rank.streamer
      prefix: '#d37efdStreamer §8| §7'
      suffix: ''
      chatPrefix: '#d37efdStreamer §8| §7%player_name% » #f5f5dc'
      placeholder-name: Streamer
    CloudPlus:
      permission: rank.cloudplus
      prefix: '#ffffff&lCloud&4Plus §8| §7'
      suffix: ''
      chatPrefix: '#ffffff&lCloud&4Plus §8| §7%player_name% » #f5f5dc'
      placeholder-name: CloudPlus
    Cloud:
      permission: rank.cloud
      prefix: '#dbdbdb&lCloud §8| §7'
      suffix: ''
      chatPrefix: '#dbdbdb&lCloud §8| §7%player_name% » #f5f5dc'
      placeholder-name: Cloud
    ender:
      permission: rank.ender
      prefix: '#b600ffEnder §8| §7'
      suffix: ''
      chatPrefix: '#b600ffEnder §8| §7%player_name% » #f5f5dc'
      placeholder-name: ender
    king:
      permission: rank.king
      prefix: '#eaff00King §8| §7'
      suffix: ''
      chatPrefix: '#eaff00King §8| §7%player_name% » #f5f5dc'
      placeholder-name: King
    dirt:
      permission: rank.dirt
      prefix: '#7e4300Dirt §8| §7'
      suffix: ''
      chatPrefix: '#7e4300Dirt §8| §7%player_name% » #f5f5dc'
      placeholder-name: Dirt
    spieler:
      permission: rank.spieler
      prefix: '#a7a7a7Spieler §8| §7'
      suffix: ''
      chatPrefix: '#a7a7a7Spieler §8| §7%player_name% » #f5f5dc'
      placeholder-name: spieler
    player:
      permission: rank.player
      prefix: '§7Player | '
      suffix: ''
      chatPrefix: '§7[&aPlayer§7] %player_name% » #f5f5dc'
      placeholder-name: Player

# ###################
# ## Placeholders ###
# ###################
placeholder:
  prefer-plugin-placeholders: true # If PB overwrites a PAPI placeholder you want to use, set this to false.
  time-format: HH:mm # If you don't know what to set here, have a look at this: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  date-format: dd-MM-yyyy
  money-decimals: 2 # The maximum decimals for the placeholder %player_money%.
  hexColorSyntax: '#000000' # Set the hex color syntax. For example 'color:000000' or just '#000000' - whatever you want. WARNING NOT WORKING CHARS: { } ( )
  world-names: # Used in the %player_world% placeholder. You can add other worlds too.
    world: Overworld
    world_nether: Nether
    world_the_end: The End

# #####################
# ## Plugin Updater ###
# #####################
update:
  notification: true # Send a message to all Admins on join if a new update is available
  autoupdater: false # With this option, the plugin will be automatically updated (No longer recommended because of some glitches)
  checkForUpdates: true

# ############################################
# ### The debug can help you find problems ###
# ############################################
debug: true
```
